In [ ]:
import torch

inputs = torch.randn((64, 8, 3))

inputs_trans = inputs.unsqueeze(1).repeat(1,20,1,1)

inputs.shape, inputs_trans.shape

(torch.Size([64, 8, 3]), torch.Size([64, 20, 8, 3]))

In [4]:
inputs[1,1,1], inputs_trans[1,:,1,1]

(tensor(1.1130),
 tensor([1.1130, 1.1130, 1.1130, 1.1130, 1.1130, 1.1130, 1.1130, 1.1130, 1.1130,
         1.1130, 1.1130, 1.1130, 1.1130, 1.1130, 1.1130, 1.1130, 1.1130, 1.1130,
         1.1130, 1.1130]))

In [ ]:
bs = 64
n_trajs = 20
gt_trajs = torch.randn((64,8,3))# torch.Size([64, 8, 3])

plan_anchor = []
for batch in range(bs):
    random_int = torch.randint(0, n_trajs, (1,)).item()
    print(random_int)
    random_anchor = torch.randn((n_trajs, 8, 3))
    print(random_anchor[random_int])
    print(gt_trajs[batch])
    random_anchor[random_int,...] = gt_trajs[batch, ...]
    print(random_anchor[random_int])
    
    plan_anchor.append(random_anchor)

plan_anchor = torch.stack(plan_anchor, dim=0)


10
tensor([[-0.4150, -0.2200,  0.1194],
        [-2.8500, -0.9177,  1.3584],
        [-1.0407, -0.3731, -0.3053],
        [ 0.6917, -0.6286, -1.1741],
        [ 1.0143, -0.2588, -0.3359],
        [-1.3509,  0.2212,  0.1668],
        [-0.2152, -0.5169, -1.2608],
        [ 0.2624, -0.6042, -0.7131]])
tensor([[ 0.1214,  1.2621,  1.3170],
        [ 0.4434, -0.4217,  0.0060],
        [-0.3063, -0.5411,  1.0533],
        [ 1.0135, -0.0059,  0.8519],
        [ 0.4002,  0.4238,  0.4741],
        [ 2.4199,  1.5588,  1.4452],
        [-0.7867, -2.3525, -0.8101],
        [-0.0676, -1.2251,  0.0794]])
tensor([[-0.6360, -0.0055,  0.6221],
        [-1.6011, -0.0034, -1.4488],
        [-0.1892,  1.6331, -0.2028],
        [-0.6939,  0.6232,  0.5329],
        [-0.3450, -0.7781, -0.0608],
        [-0.6351, -0.2062,  0.0641],
        [-2.0519, -0.4706,  1.2630],
        [-1.7495, -0.0931, -0.0037]])
18
tensor([[-1.1591,  1.3864, -0.3089],
        [ 1.0329,  0.3612, -0.2854],
        [-0.1320, -0.2905,  0

(tensor([[[ 2.4472e-01,  5.2770e-01, -2.1683e-01],
          [-7.6518e-01,  2.0031e+00,  1.3281e-01],
          [-2.0302e-01, -2.5258e-01, -1.4085e+00],
          [-6.5258e-01, -7.7934e-01,  5.1580e-03],
          [ 1.5587e+00,  5.3467e-01, -4.7695e-01],
          [ 2.1620e-01, -1.3211e+00,  4.6197e-01],
          [-1.0204e+00, -9.2854e-01, -9.9250e-01],
          [ 2.7961e-01, -1.1263e+00,  7.8234e-01]],
 
         [[-2.2176e-01, -7.8418e-03, -5.4150e-01],
          [ 1.0918e+00,  1.5777e+00,  1.0107e+00],
          [ 4.2979e-01, -1.7259e+00, -1.9804e-02],
          [-1.4357e+00,  1.0580e+00, -5.3445e-01],
          [ 7.8388e-01, -4.0895e-01, -4.3243e-01],
          [-1.0084e+00, -6.4689e-01,  1.2460e+00],
          [-5.3865e-01, -1.1092e+00, -2.0823e+00],
          [-2.2476e-01,  1.8607e+00, -6.6637e-01]],
 
         [[ 3.3094e-01, -1.1356e+00, -1.1706e-01],
          [ 4.2203e-01,  1.0095e+00, -2.6765e-01],
          [-1.9260e+00,  2.5232e-01,  6.8662e-01],
          [-5.6946e-02, -